name: validate-catalog
on:
  push:

jobs:
  test:
    name: validate catalog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REGISTRY_USERNAME }} 
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: render catalog to location
        run: ./scripts/grab_catalog.sh registry.redhat.io/redhat/redhat-operator-index:v4.15 redhat-operator-index/4.15/redhat-operator-index-v4.15.yaml

      - name: validates the modified catalog
        uses: joelanford/opm-validate@main
        with:
          catalog: redhat-operator-index/4.15
